NytrixUI.Themes.Dark      -- Default
NytrixUI.Themes.Blue      -- Blue theme
NytrixUI.Themes.Green     -- Green theme
NytrixUI.Themes.Red       -- Red theme
NytrixUI.Themes.Pastel    -- Pastel theme
NytrixUI.Themes.Midnight  -- Midnight theme
NytrixUI.Themes.Ocean     -- Ocean theme
NytrixUI.Themes.Cyberpunk -- Cyberpunk theme
NytrixUI.Themes.Gold      -- Gold theme
NytrixUI.Themes.Matrix    -- Matrix theme
